### ISSUE TITLE
Hi,how can i create a .pth  training model?

### ISSUE THREAD

**Issue by xiaopaoge** [geocompass/robosat_geoc#5]
When I  run the `python test.py`,I got the message:No model was found in directory for prediction.
I debuggered the code and find in dir no .pth model was inside.I just import shapefile to the postgis.
Many thanks!

**Comment by liii18** [comment]
Hi, the model could be obtained in earlier versions, maybe you've already got one with robosat in docker version.

**Comment by xiaopaoge** [comment]
Ok. I'll have a look.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"李昱"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月18日(星期三) 下午4:30
收件人:&nbsp;"geocompass/robosat_geoc"<robosat_geoc@noreply.github.com&gt;;
抄送:&nbsp;"孤星泪"<1060313038@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [geocompass/robosat_geoc] Hi,how can i create a .pth  training model? (#5)





 
Hi, the model could be obtained in earlier versions, maybe you've already got one with robosat in docker version.

**Comment by wucangeo** [comment]
@xiaopaoge 
Maybe you could find models in this page. 
Download one, and set the model path.

[https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/torchvision_models.py](https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/torchvision_models.py)
